### ISSUE TITLE
 Navbar with center elements also in Bootstrap.

### ISSUE THREAD

**Issue by akrish4** [Internshala-Online-Trainings/Web-Development#14]
Kindly  please add the code for navbar with elements at the center along with left and right elements. The bootstrap class for centralized elements in navbar for our better understanding and practice on navbar.

**Comment by swad007** [comment]
i will work on this issue

**Comment by Shubham56-droid** [comment]
i  will  work on this issue

**Comment by akrish4** [comment]
they wont assign you the issue and also wont accept your PR
